tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "awscli"
brew "curl"
brew "fish"
brew "git"
brew "heroku"
brew "jq"
brew "lv"
brew "mas"
brew "nkf"
brew "rbenv"
brew "tig"
brew "tmux"
brew "vim"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
cask "adobe-creative-cloud"
cask "docker"
cask "dosh"
cask "goland"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "intellij-idea"
cask "rubymine"
cask "rider"
cask "webstorm"
cask "wireshark"
cask "xmind"
mas "LINE", id: 539883307
mas "Spark - Email App by Readdle", id: 1176895641
mas "Slack", id: 803453959
mas "Todoist", id: 585829637
mas "Tweetbot 3 for Twitter", id: 1384080005
mas "Xcode", id: 497799835

